<?php
/**
 * English Language File
 */

return [
    // General
    'app_name' => 'Dormitory Management System',
    'dashboard' => 'Dashboard',
    'settings' => 'Settings',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'confirm' => 'Confirm',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'add' => 'Add',
    'search' => 'Search',
    'filter' => 'Filter',
    'all' => 'All',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'loading' => 'Loading...',
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Info',
    'done' => 'Done',
    'close' => 'Close',
    'yes' => 'Yes',
    'no' => 'No',
    'or' => 'or',
    'and' => 'and',
    'no_data' => 'No data found',
    'actions' => 'Actions',
    'quick_actions' => 'Quick actions',
    'status' => 'Status',
    'date' => 'Date',
    'time' => 'Time',
    'total' => 'Total',
    'amount' => 'Amount',
    'baht' => 'Baht',
    'month' => 'Month',
    'year' => 'Year',
    'day' => 'Day',
    'today' => 'Today',
    'yesterday' => 'Yesterday',
    'tomorrow' => 'Tomorrow',
    'this_month' => 'This Month',
    'last_month' => 'Last Month',
    'view_all' => 'View All',
    'view_details' => 'View Details',
    'print' => 'Print',
    'export' => 'Export',
    'import' => 'Import',
    'download' => 'Download',
    'upload' => 'Upload',
    'refresh' => 'Refresh',
    'reset' => 'Reset',
    'clear_data' => 'Clear',
    'home' => 'Home',
    
    // Sidebar Menu
    'menu_dashboard' => 'Dashboard',
    'menu_rooms' => 'Rooms',
    'menu_tenants' => 'Tenants',
    'menu_contracts' => 'Contracts',
    'menu_bookings' => 'Bookings',
    'menu_payments' => 'Payments',
    'menu_expenses' => 'Expenses',
    'menu_utilities' => 'Water/Electric Meters',
    'menu_repairs' => 'Repairs',
    'menu_news' => 'News',
    'menu_reports' => 'Reports',
    'menu_settings' => 'System Settings',
    'menu_account' => 'Admin Account',
    'menu_help' => 'Help',
    'menu_wizard' => 'Tenant Wizard',
    'menu_todo' => 'Todo List',
    
    // Sidebar Sub-items
    'report_tenant_list' => 'Tenant Report',
    'report_booking_list' => 'Booking Report',
    'report_stay' => 'Stay Report',
    'report_utility_list' => 'Utility Report',
    'report_revenue' => 'Revenue Report',
    'report_room_list' => 'Room Report',
    'report_payment_list' => 'Payment Report',
    'report_invoice_list' => 'Invoice Report',
    'report_repair_list' => 'Repair Report',
    'report_news_list' => 'News Report',
    'print_contract' => 'Print Contract',
    'manage_contracts' => 'Manage Contracts',
    'qr_codes' => 'Tenant QR Codes',
    'record_meters' => 'Record Meters',
    'link_google_account' => 'Link Google Account',
    'unlink_google_account' => 'Unlink Google Account',
    'manage_login_account' => 'Manage Login Account',
    'edit_hint' => 'Click to manage username, password, and recovery email',
    'edit_hint_short' => 'Click to change username/password',
    'username_label' => 'Username',
    'current_password_required' => 'Current Password (required each time)',
    'recovery_email_label' => 'Password Recovery Email',
    'new_password_optional' => 'New Password (optional)',
    'at_least_6_chars' => 'At least 6 characters',
    'confirm_new_password' => 'Confirm New Password',
    'enter_again_to_match' => 'Enter again to match',
    'save_data' => 'Save Data',
    'news_announcements' => 'Announcements',
    'pending_tasks' => 'Pending tasks',
    'items' => 'items',
    'wizard_pending_items' => 'Pending wizard items',
    'booking_needs_action' => 'Needs action: Awaiting check-in/confirmation',
    'booking_status_pending' => 'Pending booking status',
    'utility_needs_action' => 'Needs action: Rooms not yet metered',
    'utility_status_pending' => 'Pending meter reading status',
    'expense_needs_action' => 'Needs action: Awaiting payment',
    'expense_status_label' => 'Expense status',
    'payment_needs_action' => 'Needs action: Awaiting payment/review',
    'payment_status_label' => 'Payment status',
    'repair_needs_action' => 'Needs action: Awaiting/In progress',
    'repair_status_pending' => 'Pending repair status',
    
    // Rooms
    'room' => 'Room',
    'rooms' => 'Rooms',
    'room_number' => 'Room Number',
    'room_floor' => 'Floor',
    'room_type' => 'Room Type',
    'room_price' => 'Room Price',
    'room_status' => 'Room Status',
    'room_available' => 'Available',
    'room_occupied' => 'Occupied',
    'room_reserved' => 'Reserved',
    'room_maintenance' => 'Maintenance',
    'room_details' => 'Room Details',
    'add_room' => 'Add Room',
    'edit_room' => 'Edit Room',
    'delete_room' => 'Delete Room',
    
    // Tenants
    'tenant' => 'Tenant',
    'tenants' => 'Tenants',
    'tenant_name' => 'Tenant Name',
    'tenant_phone' => 'Phone',
    'tenant_email' => 'Email',
    'tenant_id_card' => 'ID Card Number',
    'tenant_address' => 'Address',
    'tenant_emergency_contact' => 'Emergency Contact',
    'add_tenant' => 'Add Tenant',
    'edit_tenant' => 'Edit Tenant',
    'tenant_details' => 'Tenant Details',
    
    // Contracts
    'contract' => 'Contract',
    'contracts' => 'Contracts',
    'contract_start' => 'Start Date',
    'contract_end' => 'End Date',
    'contract_deposit' => 'Deposit',
    'contract_status' => 'Contract Status',
    'contract_active' => 'Active',
    'contract_expired' => 'Expired',
    'contract_terminated' => 'Terminated',
    'add_contract' => 'Create Contract',
    'edit_contract' => 'Edit Contract',
    'view_contract' => 'View Contract',
    'renew_contract' => 'Renew Contract',
    
    // Bookings
    'booking' => 'Booking',
    'bookings' => 'Bookings',
    'booking_date' => 'Booking Date',
    'booking_status' => 'Booking Status',
    'booking_pending' => 'Pending',
    'booking_confirmed' => 'Confirmed',
    'booking_cancelled' => 'Cancelled',
    'booking_checkedin' => 'Checked In',
    'add_booking' => 'Add Booking',
    'confirm_booking' => 'Confirm Booking',
    'cancel_booking' => 'Cancel Booking',
    
    // Payments
    'payment' => 'Payment',
    'payments' => 'Payments',
    'payment_date' => 'Payment Date',
    'payment_amount' => 'Amount Paid',
    'payment_method' => 'Payment Method',
    'payment_status' => 'Payment Status',
    'payment_pending' => 'Pending Review',
    'payment_verified' => 'Verified',
    'payment_unpaid' => 'Unpaid',
    'payment_partial' => 'Partial',
    'payment_cash' => 'Cash',
    'payment_transfer' => 'Bank Transfer',
    'payment_promptpay' => 'PromptPay',
    'add_payment' => 'Record Payment',
    'verify_payment' => 'Verify Payment',
    'payment_slip' => 'Payment Slip',
    
    // Expenses / Bills
    'expense' => 'Expense',
    'expenses' => 'Expenses',
    'bill' => 'Bill',
    'bills' => 'Bills',
    'invoice' => 'Invoice',
    'receipt' => 'Receipt',
    'room_rent' => 'Room Rent',
    'water_bill' => 'Water Bill',
    'electric_bill' => 'Electric Bill',
    'common_fee' => 'Common Fee',
    'other_fee' => 'Other Fees',
    'total_bill' => 'Total Amount',
    'due_date' => 'Due Date',
    'overdue' => 'Overdue',
    'generate_bills' => 'Generate Bills',
    'view_bill' => 'View Bill',
    'print_bill' => 'Print Bill',
    
    // Utilities (Water/Electric Meters)
    'utilities' => 'Utilities',
    'water_meter' => 'Water Meter',
    'electric_meter' => 'Electric Meter',
    'meter_reading' => 'Meter Reading',
    'previous_reading' => 'Previous Reading',
    'current_reading' => 'Current Reading',
    'units_used' => 'Units Used',
    'water_rate' => 'Water Rate',
    'electric_rate' => 'Electric Rate',
    'per_unit' => 'per unit',
    'record_meter' => 'Record Meter',
    'meter_not_recorded' => 'Not Recorded',
    'meter_recorded' => 'Recorded',
    
    // Repairs
    'repair' => 'Repair',
    'repairs' => 'Repairs',
    'repair_title' => 'Title',
    'repair_description' => 'Description',
    'repair_status' => 'Status',
    'repair_pending' => 'Pending',
    'repair_in_progress' => 'In Progress',
    'repair_completed' => 'Completed',
    'repair_cancelled' => 'Cancelled',
    'report_repair' => 'Report Repair',
    'repair_history' => 'Repair History',
    
    // News
    'news' => 'News',
    'news_title' => 'Title',
    'news_content' => 'Content',
    'news_date' => 'Date Posted',
    'add_news' => 'Add News',
    'edit_news' => 'Edit News',
    'news_manage_title' => 'Manage Announcements',
    'news_total_label' => 'Total News',
    'news_recent_30_days_label' => 'Recent News (30 days)',
    'news_add_new_title' => 'Add New Announcement',
    'news_add_new_subtitle' => 'Publish important news and announcements',
    'news_title_placeholder' => 'Enter news title',
    'news_content_placeholder' => 'Write announcement details...',
    'news_publisher' => 'Publisher',
    'news_publisher_placeholder' => 'Publisher name',
    'news_publish_button' => 'Publish News',
    'news_list_title' => 'All Announcements',
    'news_list_subtitle' => 'News and announcement entries',
    'sort_newest' => 'Newest first',
    'sort_oldest' => 'Oldest first',
    'sort_title' => 'Title (A-Z)',
    'news_empty_title' => 'No announcements yet',
    'news_empty_hint' => 'Start by adding a new announcement from the form above',
    'show_more_items' => 'Show more (:count items)',
    'show_less' => 'Show less',
    'toggle_hide_form' => 'Hide form',
    'toggle_show_form' => 'Show form',
    'save_changes' => 'Save changes',
    'news_invalid_response' => 'Invalid server response',
    'news_update_success' => 'Announcement updated successfully',
    'news_update_error' => 'Failed to update announcement',
    'news_connection_error' => 'Connection error',
    'news_publish_success' => 'Announcement published successfully',
    'news_publish_error' => 'Failed to publish announcement',
    'news_submit_error' => 'Failed to submit data',
    'news_not_found' => 'Announcement not found',
    'news_delete_confirm_title' => 'Delete announcement',
    'news_delete_confirm_start' => 'Do you want to delete',
    'news_delete_confirm_end' => '?',
    'news_delete_error' => 'Failed to delete announcement',
    'news_delete_connection_error' => 'Connection error while deleting announcement',
    
    // Settings
    'settings_general' => 'General',
    'settings_appearance' => 'Appearance',
    'settings_rates' => 'Water/Electric Rates',
    'settings_images' => 'Images',
    'settings_system' => 'System',
    'settings_google_auth' => 'Google Authentication',
    'site_name' => 'Dormitory Name',
    'contact_phone' => 'Contact Phone',
    'contact_email' => 'Contact Email',
    'theme_color' => 'Theme Color',
    'font_size' => 'Font Size',
    'font_small' => 'Small',
    'font_normal' => 'Normal',
    'font_large' => 'Large',
    'font_xlarge' => 'Extra Large',
    'public_theme' => 'Public Theme',
    'theme_dark' => 'Dark',
    'theme_light' => 'Light',
    'theme_auto' => 'Auto',
    'use_bg_image' => 'Use Background Image',
    'logo' => 'Logo',
    'background_image' => 'Background Image',
    'upload_image' => 'Upload Image',
    'bank_info' => 'Bank Information',
    'bank_name' => 'Bank Name',
    'bank_account_name' => 'Account Name',
    'bank_account_number' => 'Account Number',
    'promptpay_number' => 'PromptPay Number',
    'save_settings' => 'Save Settings',
    'settings_saved' => 'Settings saved successfully',
    'language' => 'Language',
    'language_thai' => 'Thai',
    'language_english' => 'English',
    'select_language' => 'Select Language',
    'language_description' => 'Choose display language for the system',
    'default_view_mode' => 'Default View Mode',
    'view_grid' => 'Grid',
    'view_list' => 'List',
    'fps_threshold' => 'FPS Threshold',
    'fps_description' => 'Alert when FPS below',
    'payment_due_day' => 'Payment Due Day',
    'settings_subtitle' => 'Manage Dormitory System',
    'stat_pending' => 'Pending Bookings',
    'logo_desc' => 'Logo image displayed in the system',
    'bg_desc' => 'Hero image for home page',
    'owner_signature' => "Owner's Signature",
    'signature_desc' => 'For printing contracts automatically',
    'not_set' => 'Not configured',
    'not_uploaded' => 'Not uploaded yet',
    'signature_not_set' => 'Signature not configured',
    'payment_info_tenant_hint' => 'This information will be shown to tenants on the payment page',
    'promptpay_invalid_format' => 'PromptPay must be a 10-digit phone number or 13-digit national ID',
    'promptpay_saved_success' => 'PromptPay saved successfully',
    'invalid_server_response' => 'Invalid server response',
    'manage_logo' => 'Manage Logo',
    'manage_bg' => 'Manage Background Image',
    'current_logo' => 'Current Logo',
    'current_bg' => 'Current Background',
    'current_signature' => 'Current Signature',
    'select_existing' => 'Select from existing',
    'upload_new' => 'Upload new image',
    'click_to_select' => 'Click to select image',
    'upload_signature' => 'Upload Signature',
    'phone' => 'Phone',
    'email' => 'Email',
    'name_label' => 'Name',
    'default_view_mode_desc' => 'Applied to all admin pages',
    'public_theme_desc' => 'Theme for visitors',
    'public_theme_hint' => 'Choose theme for home, booking, and news pages',
    'use_bg_image_desc' => 'Show background image on home page',
    'theme_color_label' => 'System Background Color',
    'fps_threshold_desc' => 'Alert when FPS drops below',
    'expenses_section' => 'Expenses',
    'payment_due_label' => 'Room Payment Due Date',
    'payment_due_desc' => 'Every day :day of the month',
    'system_info_label' => 'System Information',
    'system_info_desc' => 'PHP, Database, Status',
    'backup_label' => 'Backup Data',
    'backup_desc' => 'Backup database',
    'quick_actions_label' => 'Top Menu Shortcuts',
    'quick_actions_desc' => 'Edit labels, links, and keyboard shortcuts',
    'buttons_count' => ':count buttons',
    'billing_schedule_label' => 'Billing Cycle and Due Date',
    'billing_generate_day_prefix' => 'Bill on day',
    'billing_due_day_prefix' => 'Due by day',
    'billing_schedule_saved_success' => 'Billing cycle and due date saved successfully',
    'manage_rates_label' => 'Manage Water/Electric Rates',
    'effective_from' => 'Effective from:',
    'per_unit' => 'Baht/unit',
    'google_login_status' => 'Google Login Status',
    'not_configured' => 'Not configured',
    'enabled' => 'Enabled',
    'disabled' => 'Disabled',
    
    // Reports
    'report' => 'Report',
    'reports' => 'Reports',
    'report_income' => 'Income Report',
    'report_expense' => 'Expense Report',
    'report_occupancy' => 'Occupancy Report',
    'report_payment' => 'Payment Report',
    'report_tenant' => 'Tenant Report',
    'report_monthly' => 'Monthly Report',
    'report_yearly' => 'Yearly Report',
    'export_pdf' => 'Export PDF',
    'export_excel' => 'Export Excel',
    
    // Auth & Account
    'username' => 'Username',
    'password' => 'Password',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'confirm_password' => 'Confirm Password',
    'change_password' => 'Change Password',
    'forgot_password' => 'Forgot Password',
    'remember_me' => 'Remember Me',
    'account_settings' => 'Account Settings',
    'profile' => 'Profile',
    'admin' => 'Administrator',
    'recovery_email' => 'Recovery Email',
    'link_google' => 'Link Google',
    'unlink_google' => 'Unlink Google',
    'google_linked' => 'Google Linked',
    'login_with_google' => 'Login with Google',
    
    // Validation messages
    'required_field' => 'This field is required',
    'invalid_email' => 'Invalid email format',
    'invalid_phone' => 'Invalid phone format',
    'password_mismatch' => 'Passwords do not match',
    'password_too_short' => 'Password must be at least 6 characters',
    'invalid_credentials' => 'Invalid username or password',
    'session_expired' => 'Session expired. Please login again',
    
    // Confirmation messages
    'confirm_delete' => 'Are you sure you want to delete?',
    'confirm_cancel' => 'Are you sure you want to cancel?',
    'confirm_logout' => 'Do you want to logout?',
    'action_cannot_undo' => 'This action cannot be undone',
    
    // Success messages
    'saved_successfully' => 'Saved successfully',
    'deleted_successfully' => 'Deleted successfully',
    'updated_successfully' => 'Updated successfully',
    'created_successfully' => 'Created successfully',
    
    // Error messages
    'error_occurred' => 'An error occurred',
    'try_again' => 'Please try again',
    'permission_denied' => 'Permission denied',
    'not_found' => 'Not found',
    
    // Months
    'months' => [
        1 => 'January',
        2 => 'February',
        3 => 'March',
        4 => 'April',
        5 => 'May',
        6 => 'June',
        7 => 'July',
        8 => 'August',
        9 => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December',
    ],
    'months_short' => [
        1 => 'Jan',
        2 => 'Feb',
        3 => 'Mar',
        4 => 'Apr',
        5 => 'May',
        6 => 'Jun',
        7 => 'Jul',
        8 => 'Aug',
        9 => 'Sep',
        10 => 'Oct',
        11 => 'Nov',
        12 => 'Dec',
    ],
    
    // Days of week
    'days' => [
        0 => 'Sunday',
        1 => 'Monday',
        2 => 'Tuesday',
        3 => 'Wednesday',
        4 => 'Thursday',
        5 => 'Friday',
        6 => 'Saturday',
    ],
    'days_short' => [
        0 => 'Sun',
        1 => 'Mon',
        2 => 'Tue',
        3 => 'Wed',
        4 => 'Thu',
        5 => 'Fri',
        6 => 'Sat',
    ],
    
    // Tenant Portal
    'tenant_portal' => 'Tenant Portal',
    'my_room' => 'My Room',
    'my_bills' => 'My Bills',
    'my_repairs' => 'My Repairs',
    'my_contract' => 'My Contract',
    'pay_bill' => 'Pay Bill',
    'upload_slip' => 'Upload Slip',
    
    // Stats
    'total_rooms' => 'Total Rooms',
    'available_rooms' => 'Available Rooms',
    'occupied_rooms' => 'Occupied Rooms',
    'total_tenants' => 'Total Tenants',
    'active_contracts' => 'Active Contracts',
    'pending_payments' => 'Pending Payments',
    'pending_repairs' => 'Pending Repairs',
    'monthly_income' => 'Monthly Income',
    
    // System
    'system_info' => 'System Info',
    'version' => 'Version',
    'backup' => 'Backup',
    'restore' => 'Restore',
    'last_backup' => 'Last Backup',
    'create_backup' => 'Create Backup',
    'clear_cache' => 'Clear Cache',

    // Dashboard additions
    'today_activity' => 'Today\'s Activity',
    'new_bookings' => 'New Bookings',
    'new_repairs' => 'New Repairs',
    'payments_received' => 'Payments Received',
    'occupancy_rate' => 'Occupancy Rate',
    'vacant_rooms' => 'Vacant Rooms ',
    'out_of_total_rooms' => 'of total rooms',
    'total_revenue' => 'Total Revenue',
    'from_paid_expenses' => 'From paid expenses',
    'completed_repairs' => 'Completed ',
    'jobs' => ' Jobs',
    'overview_statistics' => 'Overview Statistics',
    'booked' => 'Booked',
    'occupied' => 'Occupied',
    'cancelled' => 'Cancelled',
    'repair_report' => 'Repair Report',
    'pending' => 'Pending',
    'in_progress' => 'In Progress',
    'completed' => 'Completed',
    'revenue_chart' => 'Revenue Chart',
    'no_revenue_data' => 'No revenue data for this month',

    // More dashboard additions
    'used_rooms' => 'Used Rooms',
    'repair_requests' => 'Repair Requests',
    'monthly_revenue' => 'Monthly Revenue',
    'room_types' => 'Room Types',
    'utility_usage' => 'Utility Usage',
    'new_tenants' => 'New Tenants',
    'high_priority' => 'High Priority',
    'daily_review_tasks' => 'Tasks to review daily',
    'invoices' => 'Invoices',
    'pending_verification' => 'Pending Verification',
    'verified' => 'Verified',
    'view_details_arrow' => 'View Details →',
    'waiting_repair' => 'Waiting Repair',
    'repairing' => 'Repairing',
    'completed_already' => 'Completed',
    'occupancy_report' => 'Occupancy Report',
    'new_suffix' => 'New',
    'last_months' => 'last months',
    'last_days' => 'last days',

    // Even more dashboard additions
    'reserved' => 'Reserved',
    'regular_followup' => 'Regular Follow-up',
    'finance_and_resources' => 'Finance & Resources',
    'payment_report' => 'Payment Report',
    'total_payment_amount' => 'Total Payment',
    'income' => 'Income',
    'income_report' => 'Income Report',
    'total_income' => 'Total Income',
    'water_electric' => 'Water/Electric',
    'utility_summary_report' => 'Utility Summary Report',
    'this_month_total' => 'This month total',
    'units' => 'units',
    'vs_last_month' => 'vs last month',
    'reference_data' => 'Reference Data',
    'view_overview_and_docs' => 'View overview and documents',
    'room_info_report' => 'Room Info Report',
    'ended' => 'Ended',
    'print_contract_arrow' => 'Print Contract →',
    'data_report' => 'Data Report',
    'all_news' => 'All News',
    'completed_repair' => 'Completed',
    'revenue_baht' => 'Revenue (THB)',
    'active' => 'Active',
    'ended_label' => 'Ended',
    'vacant' => 'Vacant',
    'not_vacant' => 'Occupied',
    'water_units_label' => 'Water (Units)',
    'electric_units_label' => 'Electric (Units)',
    'payment_total_label' => 'Payment Total',
    'water_label' => 'Water',
    'electric_label' => 'Electric',
    'news_label' => 'News',
];
