<?php
/**
 * Thai Language File - ไฟล์ภาษาไทย
 */

return [
    // General
    'app_name' => 'ระบบจัดการหอพัก',
    'dashboard' => 'แดชบอร์ด',
    'settings' => 'ตั้งค่า',
    'logout' => 'ออกจากระบบ',
    'login' => 'เข้าสู่ระบบ',
    'register' => 'ลงทะเบียน',
    'save' => 'บันทึก',
    'cancel' => 'ยกเลิก',
    'confirm' => 'ยืนยัน',
    'delete' => 'ลบ',
    'edit' => 'แก้ไข',
    'add' => 'เพิ่ม',
    'search' => 'ค้นหา',
    'filter' => 'กรอง',
    'all' => 'ทั้งหมด',
    'back' => 'กลับ',
    'next' => 'ถัดไป',
    'previous' => 'ก่อนหน้า',
    'loading' => 'กำลังโหลด...',
    'success' => 'สำเร็จ',
    'error' => 'ผิดพลาด',
    'warning' => 'คำเตือน',
    'info' => 'ข้อมูล',
    'done' => 'เสร็จ',
    'close' => 'ปิด',
    'yes' => 'ใช่',
    'no' => 'ไม่',
    'or' => 'หรือ',
    'and' => 'และ',
    'no_data' => 'ไม่พบข้อมูล',
    'actions' => 'การดำเนินการ',
    'status' => 'สถานะ',
    'date' => 'วันที่',
    'time' => 'เวลา',
    'total' => 'รวม',
    'amount' => 'จำนวนเงิน',
    'baht' => 'บาท',
    'month' => 'เดือน',
    'year' => 'ปี',
    'day' => 'วัน',
    'today' => 'วันนี้',
    'yesterday' => 'เมื่อวาน',
    'tomorrow' => 'พรุ่งนี้',
    'this_month' => 'เดือนนี้',
    'last_month' => 'เดือนที่แล้ว',
    'view_all' => 'ดูทั้งหมด',
    'view_details' => 'ดูรายละเอียด',
    'print' => 'พิมพ์',
    'export' => 'ส่งออก',
    'import' => 'นำเข้า',
    'download' => 'ดาวน์โหลด',
    'upload' => 'อัพโหลด',
    'refresh' => 'รีเฟรช',
    'reset' => 'รีเซ็ต',
    'home' => 'หน้าแรก',
    
    // Sidebar Menu
    'menu_dashboard' => 'แดชบอร์ด',
    'menu_rooms' => 'ห้องพัก',
    'menu_tenants' => 'ผู้เช่า',
    'menu_contracts' => 'สัญญา',
    'menu_bookings' => 'การจอง',
    'menu_payments' => 'การชำระเงิน',
    'menu_expenses' => 'ค่าใช้จ่าย',
    'menu_utilities' => 'มิเตอร์น้ำ/ไฟ',
    'menu_repairs' => 'แจ้งซ่อม',
    'menu_news' => 'ข่าวสาร',
    'menu_reports' => 'รายงาน',
    'menu_settings' => 'ตั้งค่าระบบ',
    'menu_account' => 'บัญชีผู้ดูแล',
    'menu_help' => 'ช่วยเหลือ',
    'menu_wizard' => 'ตัวช่วยผู้เช่า',
    'menu_todo' => 'รายการงาน',
    
    // Sidebar Sub-items
    'report_tenant_list' => 'รายงานผู้เช่า',
    'report_booking_list' => 'รายงานการจอง',
    'report_stay' => 'รายงานการเข้าพัก',
    'report_utility_list' => 'รายงานสาธารณูปโภค',
    'report_revenue' => 'รายงานรายรับ',
    'report_room_list' => 'รายงานห้องพัก',
    'report_payment_list' => 'รายงานชำระเงิน',
    'report_invoice_list' => 'รายงานใบแจ้ง',
    'report_repair_list' => 'รายงานแจ้งซ่อม',
    'report_news_list' => 'รายงานข่าวสาร',
    'print_contract' => 'พิมพ์สัญญา',
    'manage_contracts' => 'จัดการสัญญา',
    'qr_codes' => 'QR Code ผู้เช่า',
    'record_meters' => 'จดมิเตอร์น้ำไฟ',
    'link_google_account' => 'เชื่อมบัญชี Google',
    'unlink_google_account' => 'ถอนการเชื่อมต่อบัญชี Google',
    'manage_login_account' => 'จัดการบัญชีเข้าสู่ระบบ',
    'edit_hint' => 'คลิกเพื่อจัดการชื่อผู้ใช้ รหัสผ่าน และอีเมลกู้คืน',
    'edit_hint_short' => 'คลิกเพื่อเปลี่ยนชื่อผู้ใช้/รหัสผ่าน',
    'username_label' => 'ชื่อผู้ใช้ (Username)',
    'current_password_required' => 'รหัสผ่านปัจจุบัน (ต้องกรอกทุกครั้ง)',
    'recovery_email_label' => 'อีเมลสำหรับกู้คืนรหัสผ่าน',
    'new_password_optional' => 'รหัสผ่านใหม่ (ไม่บังคับ)',
    'at_least_6_chars' => 'อย่างน้อย 6 ตัวอักษร',
    'confirm_new_password' => 'ยืนยันรหัสผ่านใหม่',
    'enter_again_to_match' => 'กรอกอีกครั้งให้ตรงกัน',
    'save_data' => 'บันทึกข้อมูล',
    'news_announcements' => 'ข่าวประชาสัมพันธ์',
    'pending_tasks' => 'งานรอดำเนินการ',
    'items' => 'รายการ',
    'wizard_pending_items' => 'มีรายการค้างในตัวช่วยผู้เช่า',
    'booking_needs_action' => 'ต้องจัดการ: รอเข้าพัก/รอยืนยัน',
    'booking_status_pending' => 'สถานะการจองค้าง',
    'utility_needs_action' => 'ต้องจัดการ: ห้องที่ยังไม่จดมิเตอร์',
    'utility_status_pending' => 'สถานะจดมิเตอร์น้ำไฟค้าง',
    'expense_needs_action' => 'ต้องจัดการ: รอชำระ/รอตรวจสอบ/ชำระไม่ครบ',
    'expense_status_label' => 'สถานะค่าใช้จ่าย',
    'payment_needs_action' => 'ต้องจัดการ: รอชำระ/รอตรวจสอบ',
    'payment_status_label' => 'สถานะการชำระเงิน',
    'repair_needs_action' => 'ต้องจัดการ: รอซ่อม/กำลังซ่อม',
    'repair_status_pending' => 'สถานะแจ้งซ่อมค้าง',
    
    // Rooms
    'room' => 'ห้อง',
    'rooms' => 'ห้องพัก',
    'room_number' => 'หมายเลขห้อง',
    'room_floor' => 'ชั้น',
    'room_type' => 'ประเภทห้อง',
    'room_price' => 'ราคาห้อง',
    'room_status' => 'สถานะห้อง',
    'room_available' => 'ว่าง',
    'room_occupied' => 'มีผู้เช่า',
    'room_reserved' => 'จองแล้ว',
    'room_maintenance' => 'ซ่อมบำรุง',
    'room_details' => 'รายละเอียดห้อง',
    'add_room' => 'เพิ่มห้อง',
    'edit_room' => 'แก้ไขห้อง',
    'delete_room' => 'ลบห้อง',
    
    // Tenants
    'tenant' => 'ผู้เช่า',
    'tenants' => 'ผู้เช่า',
    'tenant_name' => 'ชื่อผู้เช่า',
    'tenant_phone' => 'เบอร์โทร',
    'tenant_email' => 'อีเมล',
    'tenant_id_card' => 'เลขบัตรประชาชน',
    'tenant_address' => 'ที่อยู่',
    'tenant_emergency_contact' => 'ผู้ติดต่อฉุกเฉิน',
    'add_tenant' => 'เพิ่มผู้เช่า',
    'edit_tenant' => 'แก้ไขผู้เช่า',
    'tenant_details' => 'รายละเอียดผู้เช่า',
    
    // Contracts
    'contract' => 'สัญญา',
    'contracts' => 'สัญญา',
    'contract_start' => 'วันเริ่มสัญญา',
    'contract_end' => 'วันสิ้นสุดสัญญา',
    'contract_deposit' => 'ค่ามัดจำ',
    'contract_status' => 'สถานะสัญญา',
    'contract_active' => 'กำลังใช้งาน',
    'contract_expired' => 'หมดอายุ',
    'contract_terminated' => 'ยกเลิก',
    'add_contract' => 'สร้างสัญญา',
    'edit_contract' => 'แก้ไขสัญญา',
    'view_contract' => 'ดูสัญญา',
    'renew_contract' => 'ต่อสัญญา',
    
    // Bookings
    'booking' => 'การจอง',
    'bookings' => 'การจอง',
    'booking_date' => 'วันที่จอง',
    'booking_status' => 'สถานะการจอง',
    'booking_pending' => 'รอยืนยัน',
    'booking_confirmed' => 'ยืนยันแล้ว',
    'booking_cancelled' => 'ยกเลิก',
    'booking_checkedin' => 'เช็คอินแล้ว',
    'add_booking' => 'เพิ่มการจอง',
    'confirm_booking' => 'ยืนยันการจอง',
    'cancel_booking' => 'ยกเลิกการจอง',
    
    // Payments
    'payment' => 'การชำระเงิน',
    'payments' => 'การชำระเงิน',
    'payment_date' => 'วันที่ชำระ',
    'payment_amount' => 'ยอดชำระ',
    'payment_method' => 'วิธีการชำระ',
    'payment_status' => 'สถานะการชำระ',
    'payment_pending' => 'รอตรวจสอบ',
    'payment_verified' => 'ตรวจสอบแล้ว',
    'payment_unpaid' => 'ยังไม่ชำระ',
    'payment_partial' => 'ชำระบางส่วน',
    'payment_cash' => 'เงินสด',
    'payment_transfer' => 'โอนเงิน',
    'payment_promptpay' => 'พร้อมเพย์',
    'add_payment' => 'บันทึกการชำระ',
    'verify_payment' => 'ตรวจสอบการชำระ',
    'payment_slip' => 'สลิปการโอน',
    
    // Expenses / Bills
    'expense' => 'ค่าใช้จ่าย',
    'expenses' => 'ค่าใช้จ่าย',
    'bill' => 'บิล',
    'bills' => 'บิล',
    'invoice' => 'ใบแจ้งหนี้',
    'receipt' => 'ใบเสร็จ',
    'room_rent' => 'ค่าเช่าห้อง',
    'water_bill' => 'ค่าน้ำ',
    'electric_bill' => 'ค่าไฟ',
    'common_fee' => 'ค่าส่วนกลาง',
    'other_fee' => 'ค่าอื่นๆ',
    'total_bill' => 'ยอดรวม',
    'due_date' => 'วันครบกำหนด',
    'overdue' => 'เกินกำหนด',
    'generate_bills' => 'สร้างบิล',
    'view_bill' => 'ดูบิล',
    'print_bill' => 'พิมพ์บิล',
    
    // Utilities (Water/Electric Meters)
    'utilities' => 'มิเตอร์',
    'water_meter' => 'มิเตอร์น้ำ',
    'electric_meter' => 'มิเตอร์ไฟ',
    'meter_reading' => 'จดมิเตอร์',
    'previous_reading' => 'เลขก่อนหน้า',
    'current_reading' => 'เลขปัจจุบัน',
    'units_used' => 'หน่วยที่ใช้',
    'water_rate' => 'อัตราค่าน้ำ',
    'electric_rate' => 'อัตราค่าไฟ',
    'per_unit' => 'ต่อหน่วย',
    'record_meter' => 'บันทึกมิเตอร์',
    'meter_not_recorded' => 'ยังไม่ได้จดมิเตอร์',
    'meter_recorded' => 'จดมิเตอร์แล้ว',
    
    // Repairs
    'repair' => 'แจ้งซ่อม',
    'repairs' => 'แจ้งซ่อม',
    'repair_title' => 'หัวข้อ',
    'repair_description' => 'รายละเอียด',
    'repair_status' => 'สถานะ',
    'repair_pending' => 'รอดำเนินการ',
    'repair_in_progress' => 'กำลังดำเนินการ',
    'repair_completed' => 'เสร็จสิ้น',
    'repair_cancelled' => 'ยกเลิก',
    'report_repair' => 'แจ้งซ่อม',
    'repair_history' => 'ประวัติการซ่อม',
    
    // News
    'news' => 'ข่าวสาร',
    'news_title' => 'หัวข้อข่าว',
    'news_content' => 'เนื้อหา',
    'news_date' => 'วันที่ลง',
    'add_news' => 'เพิ่มข่าว',
    'edit_news' => 'แก้ไขข่าว',
    
    // Settings
    'settings_general' => 'ทั่วไป',
    'settings_appearance' => 'การแสดงผล',
    'settings_rates' => 'อัตราค่าน้ำ/ไฟ',
    'settings_images' => 'รูปภาพ',
    'settings_system' => 'ระบบ',
    'settings_google_auth' => 'Google Authentication',
    'site_name' => 'ชื่อหอพัก',
    'contact_phone' => 'เบอร์โทรติดต่อ',
    'contact_email' => 'อีเมลติดต่อ',
    'theme_color' => 'สีธีม',
    'font_size' => 'ขนาดตัวอักษร',
    'font_small' => 'เล็ก',
    'font_normal' => 'ปกติ',
    'font_large' => 'ใหญ่',
    'font_xlarge' => 'ใหญ่มาก',
    'public_theme' => 'ธีมหน้าสาธารณะ',
    'theme_dark' => 'มืด',
    'theme_light' => 'สว่าง',
    'theme_auto' => 'อัตโนมัติ',
    'use_bg_image' => 'ใช้ภาพพื้นหลัง',
    'logo' => 'โลโก้',
    'background_image' => 'ภาพพื้นหลัง',
    'upload_image' => 'อัพโหลดรูป',
    'bank_info' => 'ข้อมูลธนาคาร',
    'bank_name' => 'ชื่อธนาคาร',
    'bank_account_name' => 'ชื่อบัญชี',
    'bank_account_number' => 'เลขบัญชี',
    'promptpay_number' => 'หมายเลขพร้อมเพย์',
    'save_settings' => 'บันทึกการตั้งค่า',
    'settings_saved' => 'บันทึกการตั้งค่าเรียบร้อย',
    'language' => 'ภาษา',
    'language_thai' => 'ไทย',
    'language_english' => 'English',
    'select_language' => 'เลือกภาษา',
    'language_description' => 'เลือกภาษาที่ใช้แสดงในระบบ',
    'default_view_mode' => 'รูปแบบการแสดงผลเริ่มต้น',
    'view_grid' => 'ตาราง',
    'view_list' => 'รายการ',
    'fps_threshold' => 'FPS Threshold',
    'fps_description' => 'แจ้งเตือนเมื่อ FPS ต่ำกว่า',
    'payment_due_day' => 'วันครบกำหนดชำระ',
    'settings_subtitle' => 'จัดการระบบหอพัก',
    'stat_pending' => 'รอจอง',
    'logo_desc' => 'รูปโลโก้ที่แสดงในระบบ',
    'bg_desc' => 'ภาพ Hero หน้าแรก',
    'owner_signature' => 'ลายเซ็นเจ้าของหอ',
    'signature_desc' => 'สำหรับพิมพ์สัญญาอัตโนมัติ',
    'not_set' => 'ยังไม่ได้ตั้งค่า',
    'not_uploaded' => 'ยังไม่ได้อัพโหลด',
    'signature_not_set' => 'ยังไม่ได้ตั้งค่าลายเซ็น',
    'manage_logo' => 'จัดการโลโก้',
    'manage_bg' => 'จัดการภาพพื้นหลัง',
    'current_logo' => 'โลโก้ปัจจุบัน',
    'current_bg' => 'ภาพพื้นหลังปัจจุบัน',
    'current_signature' => 'ลายเซ็นปัจจุบัน',
    'select_existing' => 'เลือกจากรูปที่มี',
    'upload_new' => 'อัพโหลดรูปใหม่',
    'click_to_select' => 'คลิกเพื่อเลือกรูป',
    'upload_signature' => 'อัพโหลดลายเซ็น',
    'phone' => 'เบอร์โทรศัพท์',
    'email' => 'อีเมล',
    'name_label' => 'ชื่อ',
    'default_view_mode_desc' => 'ใช้กับทุกหน้าแอดมิน',
    'public_theme_desc' => 'ธีมสำหรับผู้เยี่ยมชม',
    'public_theme_hint' => 'เลือกธีมสำหรับหน้าแรก, หน้าจองห้อง และหน้าข่าวสาร',
    'use_bg_image_desc' => 'แสดงภาพพื้นหลังบนหน้าแรก',
    'theme_color_label' => 'สีพื้นหลังระบบ',
    'fps_threshold_desc' => 'แจ้งเตือนเมื่อ FPS ต่ำกว่า',
    'expenses_section' => 'ค่าใช้จ่าย',
    'payment_due_label' => 'กำหนดชำระค่าห้อง',
    'payment_due_desc' => 'ทุกวันที่ :day ของเดือน',
    'system_info_label' => 'ข้อมูลระบบ',
    'system_info_desc' => 'PHP, Database, สถานะ',
    'backup_label' => 'สำรองข้อมูล',
    'backup_desc' => 'Backup ฐานข้อมูล',
    'quick_actions_label' => 'ปุ่มลัดเมนูด้านบน',
    'quick_actions_desc' => 'แก้ชื่อ ลิงก์ และคีย์ลัดของ quick actions',
    'buttons_count' => ':count ปุ่ม',
    'manage_rates_label' => 'จัดการอัตราค่าน้ำค่าไฟ',
    'effective_from' => 'เริ่มใช้:',
    'per_unit' => 'บาท/หน่วย',
    'google_login_status' => 'สถานะ Google Login',
    'not_configured' => 'ยังไม่ได้ตั้งค่า',
    'enabled' => 'เปิดใช้งาน',
    'disabled' => 'ปิด',
    
    // Reports
    'report' => 'รายงาน',
    'reports' => 'รายงาน',
    'report_income' => 'รายงานรายรับ',
    'report_expense' => 'รายงานรายจ่าย',
    'report_occupancy' => 'รายงานอัตราการเข้าพัก',
    'report_payment' => 'รายงานการชำระเงิน',
    'report_tenant' => 'รายงานผู้เช่า',
    'report_monthly' => 'รายงานประจำเดือน',
    'report_yearly' => 'รายงานประจำปี',
    'export_pdf' => 'ส่งออก PDF',
    'export_excel' => 'ส่งออก Excel',
    
    // Auth & Account
    'username' => 'ชื่อผู้ใช้',
    'password' => 'รหัสผ่าน',
    'current_password' => 'รหัสผ่านปัจจุบัน',
    'new_password' => 'รหัสผ่านใหม่',
    'confirm_password' => 'ยืนยันรหัสผ่าน',
    'change_password' => 'เปลี่ยนรหัสผ่าน',
    'forgot_password' => 'ลืมรหัสผ่าน',
    'remember_me' => 'จดจำฉัน',
    'account_settings' => 'ตั้งค่าบัญชี',
    'profile' => 'โปรไฟล์',
    'admin' => 'ผู้ดูแลระบบ',
    'recovery_email' => 'อีเมลกู้คืน',
    'link_google' => 'เชื่อมต่อ Google',
    'unlink_google' => 'ยกเลิกการเชื่อมต่อ Google',
    'google_linked' => 'เชื่อมต่อ Google แล้ว',
    'login_with_google' => 'เข้าสู่ระบบด้วย Google',
    
    // Validation messages
    'required_field' => 'กรุณากรอกข้อมูล',
    'invalid_email' => 'รูปแบบอีเมลไม่ถูกต้อง',
    'invalid_phone' => 'รูปแบบเบอร์โทรไม่ถูกต้อง',
    'password_mismatch' => 'รหัสผ่านไม่ตรงกัน',
    'password_too_short' => 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'invalid_credentials' => 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    'session_expired' => 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่',
    
    // Confirmation messages
    'confirm_delete' => 'คุณแน่ใจหรือไม่ที่จะลบ?',
    'confirm_cancel' => 'คุณแน่ใจหรือไม่ที่จะยกเลิก?',
    'confirm_logout' => 'คุณต้องการออกจากระบบหรือไม่?',
    'action_cannot_undo' => 'การดำเนินการนี้ไม่สามารถย้อนกลับได้',
    
    // Success messages
    'saved_successfully' => 'บันทึกเรียบร้อยแล้ว',
    'deleted_successfully' => 'ลบเรียบร้อยแล้ว',
    'updated_successfully' => 'อัพเดทเรียบร้อยแล้ว',
    'created_successfully' => 'สร้างเรียบร้อยแล้ว',
    
    // Error messages
    'error_occurred' => 'เกิดข้อผิดพลาด',
    'try_again' => 'กรุณาลองใหม่อีกครั้ง',
    'permission_denied' => 'ไม่มีสิทธิ์เข้าถึง',
    'not_found' => 'ไม่พบข้อมูล',
    
    // Thai months
    'months' => [
        1 => 'มกราคม',
        2 => 'กุมภาพันธ์',
        3 => 'มีนาคม',
        4 => 'เมษายน',
        5 => 'พฤษภาคม',
        6 => 'มิถุนายน',
        7 => 'กรกฎาคม',
        8 => 'สิงหาคม',
        9 => 'กันยายน',
        10 => 'ตุลาคม',
        11 => 'พฤศจิกายน',
        12 => 'ธันวาคม',
    ],
    'months_short' => [
        1 => 'ม.ค.',
        2 => 'ก.พ.',
        3 => 'มี.ค.',
        4 => 'เม.ย.',
        5 => 'พ.ค.',
        6 => 'มิ.ย.',
        7 => 'ก.ค.',
        8 => 'ส.ค.',
        9 => 'ก.ย.',
        10 => 'ต.ค.',
        11 => 'พ.ย.',
        12 => 'ธ.ค.',
    ],
    
    // Days of week
    'days' => [
        0 => 'อาทิตย์',
        1 => 'จันทร์',
        2 => 'อังคาร',
        3 => 'พุธ',
        4 => 'พฤหัสบดี',
        5 => 'ศุกร์',
        6 => 'เสาร์',
    ],
    'days_short' => [
        0 => 'อา.',
        1 => 'จ.',
        2 => 'อ.',
        3 => 'พ.',
        4 => 'พฤ.',
        5 => 'ศ.',
        6 => 'ส.',
    ],
    
    // Tenant Portal
    'tenant_portal' => 'ระบบผู้เช่า',
    'my_room' => 'ห้องของฉัน',
    'my_bills' => 'บิลของฉัน',
    'my_repairs' => 'แจ้งซ่อม',
    'my_contract' => 'สัญญาของฉัน',
    'pay_bill' => 'ชำระบิล',
    'upload_slip' => 'อัพโหลดสลิป',
    
    // Stats
    'total_rooms' => 'ห้องทั้งหมด',
    'available_rooms' => 'ห้องว่าง',
    'occupied_rooms' => 'ห้องมีผู้เช่า',
    'total_tenants' => 'ผู้เช่าทั้งหมด',
    'active_contracts' => 'สัญญาที่ใช้งาน',
    'pending_payments' => 'รอชำระ',
    'pending_repairs' => 'รอซ่อม',
    'monthly_income' => 'รายได้ประจำเดือน',
    
    // System
    'system_info' => 'ข้อมูลระบบ',
    'version' => 'เวอร์ชัน',
    'backup' => 'สำรองข้อมูล',
    'restore' => 'กู้คืนข้อมูล',
    'last_backup' => 'สำรองล่าสุด',
    'create_backup' => 'สร้างไฟล์สำรอง',
    'clear_cache' => 'ล้างแคช',
];
